### ISSUE TITLE
java.lang.NoSuchMethodError: javax.net.ssl.SSLContext.getDefault API 8

### ISSUE THREAD

**Issue by Caponete** [koush/ion#538]
Im working with ION 2.1.3 and have this error:

04-11 17:05:38.592: E/AndroidRuntime(1169): FATAL EXCEPTION: ion-ion
04-11 17:05:38.592: E/AndroidRuntime(1169): java.lang.NoSuchMethodError: javax.net.ssl.SSLContext.getDefault
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:50)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:82)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:117)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:303)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:50)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:189)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
04-11 17:05:38.592: E/AndroidRuntime(1169):     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

Exists an alternative for 8 API level?

Regards
Santiago.

**Comment by sootood** [comment]
i have this problem too, i dont know what to do if you know please answer
